# Generated by Django 3.1.7 on 2021-04-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='buyer',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product',
            field=models.CharField(max_length=100),
        ),
    ]
